#MODEL:
model_name: exp48_decoder26
model_type: experimental2
num_classes: 6
ignore_value: 255
pretrained_backbone: False

#OPTIM:
epochs: 1000
max_epochs: 1000
resume: False
lr: 0.05
momentum: 0.9
weight_decay: 0.0001
class_weight: null
bn_weight_decay: False
bn_precise_stats: False
bn_precise_num_samples: 600
lr_scheduler: poly
poly_power: 0.9
warmup_iters: 3000
warmup_factor: 0.1

#TRAIN:
mixed_precision: True
run: 1
RNG_seed: 0
loss_type: cross_entropy
eval_while_train: True
exclude_classes: [14,15,16]

#benchmark
warmup_iter: 10
num_iter: 100
benchmark_loader: True
benchmark_model: True

#dataset
dataset_name: hit_uav
dataset_dir: /users/local/j20morli/Schneider/third_party/HIT-UAV/normal_json/
batch_size: 8
train_min_size: 512
train_max_size: 640
train_crop_size: [512,512]
val_input_size: 512
val_label_size: 512
aug_mode: randaug_reduced
num_workers: 6
class_uniform_pct: 0.5
train_split: trainval
val_split: val
max_eval: 600
validate_train_loader: False
eval_print_every: 10000
train_print_every: 10000

#checkpoint
pretrained_path: ''
save_every_k_epochs: 25
save_last_k_epochs: 20
save_dir: checkpoints
log_dir: training_log
save_name: hit_uav_exp48_decoder26_trainval_500_epochs
save_best_path: checkpoints/hit_uav_exp48_decoder26_best
save_latest_path: checkpoints/hit_uav_exp48_decoder26_latest
